name: "docker/build-push-ecr"
description: ""
inputs:
  dockerfile:
    description: ""
    default: "Dockerfile"
  context:
    description: ""
    default: "."
  ecr_repository:
    description: ""
    required: true
  ecr_access_key_id:
    description: ""
    default: ${{ secrets.AWS_ACCESS_KEY_ID }}
  ecr_secret_access_key:
    description: ""
    default: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: rlespinasse/git-commit-data-action@v1
    - uses: josStorer/get-current-time@v2 
      id: current-time
      with:
        format: "YYYY-MM-DDTHH:mm:ss.SSSZ"
        utcOffset: "+09:00"
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.ecr_access_key_id }}
        aws-secret-access-key: ${{ inputs.ecr_secret_access_key }}
        aws-region: ap-northeast-1
    - uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr
        
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}
        flavor: |
          latest=false
        tags: |
          type=ref,event=tag
          type=raw,value={{sha}}
          type=edge
    - uses: docker/setup-buildx-action@v1 
    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ runner.arch }}-buildx-${{ inputs.ecr_repository }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-buildx-${{ inputs.ecr_repository }}-
    - uses: docker/build-push-action@v2
      id: build-push-image
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        build-args: |
          MIEERU_RELEASE_VERSION=${{ env.GIT_COMMIT_SHORT_SHA }}
          MIEERU_RELEASE_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
          MIEERU_RELEASE_DATE=${{ steps.current-time.outputs.formattedTime }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - name: update docker build cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache